### ISSUE TITLE
Structure non valide 

### ISSUE THREAD

**Issue by baptistelinel** [baptistelinel/Administrable-Blog#1]
La structure divisée en plusieurs bundle ne respecte pas la philosophie Symfony qui voudrait que chaque bundle puisse être indépendant de la structure générale. Dans notre cas, tous les bundles de l'applications sont liés.

Il faut donc repenser la structure de l'application et créer un unique bundle : BlogBundle.

**Comment by baptistelinel** [comment]
Création d'une nouvelle branche struct pour résoudre le problème.

**Comment by ChristopheVilleger** [comment]
Très bonne idée :+1:
